# ===================================================================
# Spring Boot Application Configuration
# ===================================================================

spring:
  application:
    name: bloomtoget

  profiles:
    active: local

  # ===================================================================
  # Database Configuration (MySQL)
  # ===================================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # ===================================================================
  # JPA / Hibernate Configuration
  # ===================================================================
  jpa:
    hibernate:
      ddl-auto: validate  # 개발: update, 운영: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        # Spring Boot 기본 명명 전략
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    show-sql: false  # SQL 로깅은 logging.level.org.hibernate.SQL로 제어
    open-in-view: false  # OSIV 비활성화 (LazyInitializationException 방지 + 성능)

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

        # 쿼리 성능 통계 (개발용)
        generate_statistics: true

  # ===================================================================
  # Development Tools
  # ===================================================================
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# ===================================================================
# Server Configuration
# ===================================================================
server:
  port: 8080
  servlet:
    context-path: /

# ===================================================================
# API Documentation
# ===================================================================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: asc
  show-actuator: false
